global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:

  - job_name: 'grpc_health_proxy'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['localhost:9000']
